import { useState } from 'react';
import { LayoutDashboard, ChartNoAxesCombined, Users, ShieldCheck, ChevronDown, ArrowUpRight, ArrowDownRight, Bell, Search, Sparkles, Send, Building2, Wallet, Radio, Headphones, Target, ShoppingBag, Landmark, Briefcase, X, Check, Download, Globe, Activity, Menu } from 'lucide-react';
import { departments, business, initialUsers, drivers } from './data';
import { allowedDepartments, resolveDepartment } from './access.mjs';
import { selectCustomers, summariseCustomers, datasetBadge } from './analytics.mjs';
import { sampleCustomers } from './customerSamples';
import CustomerAnalytics from './CustomerAnalytics';
import OmastaAssistant from './OmastaAssistant';
import './customerAnalytics.css';

const icons = {B2C:Users, B2B:Building2, 'Orange Money':Wallet, 'Customer Service':Headphones, 'Retention / CRM':Target, Sales:ShoppingBag, Network:Radio, Finance:Landmark, 'Executive Management':Briefcase};
const fmt = n => n.toLocaleString('en-US');
function Trend({color='#ff7900'}) { return <svg viewBox="0 0 180 38" className="sparkline" aria-label="Illustrative trend"><path d="M0 34 L20 26 L40 30 L60 19 L80 24 L100 13 L120 17 L140 7 L160 11 L180 2" fill="none" stroke={color} strokeWidth="2.5"/><path d="M0 34 L20 26 L40 30 L60 19 L80 24 L100 13 L120 17 L140 7 L160 11 L180 2 L180 38 L0 38Z" fill={color} opacity=".08"/></svg>; }
function MapPanel() {
  const tiles = Array.from({length:72}, (_,i) => { const row=Math.floor(i/8), col=i%8; const colors=['#ff7900','#f5b644','#f9d269','#ff9b32','#1db778']; return <rect key={i} x={col*25+((row%2)*7)} y={row*25} width="25" height="25" fill={colors[(row*3+col*7)%5]} stroke="white" strokeWidth="1"/>; });
  return <div className="map-area"><svg viewBox="0 0 330 260" role="img" aria-label="Illustrative Sierra Leone hotspot map, not district boundaries"><defs><clipPath id="country"><path d="M118 23 L158 30 185 17 206 45 226 52 222 88 247 103 235 138 257 158 229 190 211 219 182 234 164 219 137 220 118 203 98 189 78 167 68 140 83 115 78 87 97 67 98 43Z"/></clipPath></defs><g clipPath="url(#country)"><g transform="translate(58 15)">{tiles}</g></g><path d="M118 23 L158 30 185 17 206 45 226 52 222 88 247 103 235 138 257 158 229 190 211 219 182 234 164 219 137 220 118 203 98 189 78 167 68 140 83 115 78 87 97 67 98 43Z" fill="none" stroke="#fff" strokeWidth="3"/><circle cx="90" cy="137" r="6" fill="#e74444" stroke="white" strokeWidth="3"/><g fill="#344054" fontSize="11" fontWeight="600"><text x="15" y="125">Western Area</text><text x="15" y="142" fill="#e74444">22.6%</text><text x="236" y="66">Northern</text><text x="236" y="83">14.8%</text><text x="252" y="174">Eastern</text><text x="252" y="191">9.7%</text><text x="108" y="250">Southern · 8.4%</text></g></svg><div className="map-legend"><span><i style={{background:'#ff7900'}}/>High risk</span><span><i style={{background:'#f9d269'}}/>Moderate</span><span><i style={{background:'#1db778'}}/>Low risk</span></div></div>;
}
export default function App() {
  const [users,setUsers]=useState(initialUsers), [userId,setUserId]=useState(1), [requested,setRequested]=useState('All departments'), [page,setPage]=useState('overview'), [period,setPeriod]=useState('Last 30 days'), [search,setSearch]=useState(''), [editing,setEditing]=useState(null), [notice,setNotice]=useState(''), [mobile,setMobile]=useState(false);
  const user=users.find(u=>u.id===userId), allowed=allowedDepartments(user,departments), selected=resolveDepartment(user,requested,departments), all=selected==='All departments', record=business.find(d=>d.name===selected), visible=all?business:record?[record]:[];
  const totals=visible.reduce((a,d)=>({customers:a.customers+d.customers,risk:a.risk+d.risk,revenue:a.revenue+d.revenue}),{customers:0,risk:0,revenue:0});
  const [dataset,setDataset]=useState({rows:sampleCustomers,source:'sample',name:'Sample customer dataset',revision:0});
  const customerRows=selectCustomers(dataset.rows,selected,allowed);
  const customerSummary=summariseCustomers(customerRows);
  const canViewCustomers=allowed.some(d=>d==='B2C'||d==='B2B');
  const multiplier=period==='Last 7 days'?.25:period==='Last 90 days'?2.7:1;
  function choose(d) {setRequested(d);setPage('overview');setMobile(false);}
  function exportReport() { const rows=['Department,Customers,Customers at risk,Churn rate,Revenue at risk (SLE million)',...visible.map(d=>`${d.name},${d.customers},${d.risk},${d.rate},${d.revenue}`),'Sample data only']; const url=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'})); const a=document.createElement('a');a.href=url;a.download='orange-churn-sample-report.csv';a.click();URL.revokeObjectURL(url);setNotice('Sample report downloaded.'); }
  return <div className="app"><aside className={`sidebar ${mobile?'mobile-open':''}`}><div className="brand-square">orange<span>■</span></div><div className="workspace-label">INTELLIGENCE WORKSPACE</div><button className={page==='overview'&&all?'nav active':'nav'} onClick={()=>choose(allowed[0])}><LayoutDashboard size={18}/>Overview</button><div className="nav-section">DEPARTMENTS <span>{allowed.filter(d=>d!=='All departments').length}</span></div>{allowed.filter(d=>d!=='All departments').map(d=>{const Icon=icons[d];return <button key={d} className={selected===d&&page==='overview'?'nav active':'nav'} onClick={()=>choose(d)}><Icon size={17}/>{d}</button>;})}<div className="nav-divider"/>{canViewCustomers&&<button className={page==='customers'?'nav active':'nav'} onClick={()=>{if(!['All departments','B2C','B2B'].includes(selected))setRequested(allowed.find(d=>d==='B2C'||d==='B2B'));setPage('customers');setMobile(false);}}><Users size={18}/>Customer analysis</button>}{user.role==='Super admin'&&<button className={page==='team'?'nav active':'nav'} onClick={()=>{setPage('team');setMobile(false);}}><ShieldCheck size={18}/>Team & access</button>}<button className={page==='reports'?'nav active':'nav'} onClick={()=>{setPage('reports');setMobile(false);}}><ChartNoAxesCombined size={18}/>Reports</button><div className="sidebar-bottom"><div className="country"><span className="flag"/>Sierra Leone <Globe size={15}/></div><p>One Orange.<br/><strong>Stronger connections.</strong></p><span className="workspace-status"><i/> Preview workspace</span></div></aside>
  <div className="workspace"><header className="topbar"><button className="mobile-toggle icon-button" aria-label="Toggle navigation" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><div className="brand"><span className="brand-mark">O</span><div>Orange <strong>Intelligence</strong><small>Customer insights. Meaningful action.</small></div></div><div className="topbar-right"><label className="department-switch"><Building2 size={16}/><select aria-label="Switch department" value={selected??''} onChange={e=>choose(e.target.value)}>{allowed.length?allowed.map(d=><option key={d}>{d}</option>):<option value="">No department assigned</option>}</select><ChevronDown size={14}/></label><button className="icon-button notification" aria-label="Notifications" onClick={()=>setNotice('You have 3 sample insights to review on the overview.')}><Bell size={19}/><i/></button><span className="topbar-line"/><div className="avatar">{user.initials}</div><label className="profile"><select aria-label="Preview as administrator" value={userId} onChange={e=>{setUserId(Number(e.target.value));setRequested('All departments');setPage('overview');}}>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><small>{user.role} · Demo identity</small></label></div></header>
  <main><div className="breadcrumb">Workspace <span>/</span> {page==='team'?'Team & access':selected} <span>/</span><strong>{page==='reports'?'Reports':page==='customers'?'Customer analysis':page==='team'?'Responsibilities':'Overview'}</strong></div><div className="page-heading"><div><div className="eyebrow"><i/> ORANGE SIERRA LEONE</div><h1>{page==='team'?'People, with purpose.':page==='reports'?'Reports & insights':page==='customers'?'Understand every customer.':all?'Every connection counts.':`${selected} intelligence`}</h1><p>{page==='team'?'Give each administrator the access they need to make an impact.':page==='customers'?'Explore plans, usage, charges and support with OMASTA intelligence.':all?'Your customer relationships, across every Orange business.':'Understand your department. Take the next best action.'}</p></div><div className="heading-actions"><span className="demo-badge">{page==='customers'?datasetBadge(dataset.source):'Sample data'}</span>{page!=='team'&&page!=='customers'&&<select className="period" aria-label="Reporting period" value={period} onChange={e=>setPeriod(e.target.value)}><option>Last 7 days</option><option>Last 30 days</option><option>Last 90 days</option></select>}{page!=="customers"&&<button className="secondary-button" onClick={exportReport}><Download size={15}/>Export report</button>}</div></div>
  {notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
  {page==='team'&&user.role==='Super admin'?<section className="panel team-panel"><div className="panel-heading"><div><h2>Administrator responsibilities</h2><p>Assignments apply to this preview session.</p></div><span className="pill">{users.length} administrators</span></div><div className="team-table">{users.map(u=><div className="team-row" key={u.id}><div className="avatar">{u.initials}</div><div className="person"><strong>{u.name}</strong><small>{u.email}</small></div><span className="role-pill">{u.role}</span><div className="assignments">{u.role==='Super admin'?<span>All departments</span>:u.departments.length?u.departments.map(d=><span key={d}>{d}</span>):<span>No access assigned</span>}</div>{u.role!=='Super admin'&&<button className="secondary-button" onClick={()=>setEditing({...u,departments:[...u.departments]})}>Edit access</button>}</div>)}</div><div className="access-note"><ShieldCheck size={20}/><div><strong>Access follows responsibility</strong><p>Switch the demo identity in the top bar to review each admin’s experience. Production requires authenticated users and server-side authorisation.</p></div></div></section>:!selected?<section className="panel empty"><ShieldCheck/><h2>No department assigned</h2><p>A super admin must assign access to this account.</p></section>:page==='customers'&&canViewCustomers?<CustomerAnalytics key={[selected,userId,dataset.revision].join("-")} rows={customerRows} department={selected} source={dataset.source} sourceName={dataset.name} canImport={user.role==='Super admin'} onImport={(rows,name)=>setDataset(previous=>({rows,name,source:'imported',revision:previous.revision+1}))} onReset={()=>setDataset(previous=>({rows:sampleCustomers,name:'Sample customer dataset',source:'sample',revision:previous.revision+1}))}/>:<>
  <div className="metrics">{[{label:'Total customers',value:fmt(totals.customers),change:'2.3%',note:'customer base growth',Icon:Users,color:'orange'},{label:'Customers at risk',value:fmt(Math.round(totals.risk*multiplier)),change:'12.7%',note:'needs your attention',Icon:Activity,color:'red'},{label:'High-risk customers',value:fmt(Math.round(totals.risk*.39*multiplier)),change:'5.0%',note:'priority for retention',Icon:Target,color:'purple'},{label:'Revenue at risk',value:`SLE ${(totals.revenue*multiplier).toFixed(1)}M`,change:'14.2%',note:'estimated exposure',Icon:Landmark,color:'green'}].map(m=><section className="metric" key={m.label}><div className="metric-top"><span>{m.label}</span><div className={`metric-icon ${m.color}`}><m.Icon size={19}/></div></div><strong>{visible.length?m.value:'—'}</strong><div className="metric-bottom"><span className={m.color==='orange'?'positive':'negative'}><ArrowUpRight size={14}/>{visible.length?m.change:'—'}</span><span>{m.note}</span></div></section>)}</div>
  {!visible.length&&<div className="notice">{selected} is included in the workspace. Department data has not been connected yet.</div>}
  <div className="dashboard-grid"><div className="dashboard-main"><div className="charts"><section className="panel"><div className="panel-heading"><div><h2>Churn by business area</h2><p>Where our relationships need attention</p></div><span className="pill">%</span></div><div className="bar-chart"><div className="axis"><span>20%</span><span>15%</span><span>10%</span><span>5%</span><span>0%</span></div><div className="bars">{visible.map(d=><button className="bar-item" key={d.name} onClick={()=>choose(d.name)} aria-label={`Open ${d.name}, churn ${d.rate}%`}><strong>{d.rate}%</strong><div style={{height:`${d.rate*8}px`,background:d.color}}/><span>{d.name}</span></button>)}</div></div><div className="chart-foot"><span className="negative"><ArrowUpRight size={14}/> Retention opportunity</span><span>Sample period</span></div></section><section className="panel"><div className="panel-heading"><div><h2>Regional hotspots</h2><p>Illustrative risk distribution</p></div><span className="pill">SL</span></div><MapPanel/></section></div>
  <section className="panel departments-panel"><div className="panel-heading"><div><h2>Business area intelligence</h2><p>From a bigger picture to a focused action</p></div><label className="business-search"><Search size={13}/><input aria-label="Filter business areas" placeholder="Find a business area" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="business-cards">{visible.filter(d=>d.name.toLowerCase().includes(search.toLowerCase())).map(d=>{const Icon=icons[d.name];return <button className="business-card" key={d.name} onClick={()=>choose(d.name)}><div className="business-title"><span style={{background:`${d.color}18`,color:d.color}}><Icon size={18}/></span><div><strong>{d.name}</strong><small>{d.label}</small></div><ArrowUpRight size={16}/></div><div className="business-rate"><strong>{d.rate}<small>%</small></strong><span className={d.trend.startsWith('−')?'positive':'negative'}>{d.trend}%</span></div><Trend color={d.color}/><div className="business-details"><span>At-risk customers<strong>{fmt(d.risk)}</strong></span><span>Revenue at risk<strong>SLE {d.revenue}M</strong></span></div><div className="business-link">Explore dashboard <ArrowUpRight size={14}/></div></button>;})}</div>{search&&!visible.some(d=>d.name.toLowerCase().includes(search.toLowerCase()))&&<p>No business areas match your search.</p>}</section>
  <section className="panel"><div className="panel-heading"><div><h2>Next best actions</h2><p>Turn insight into stronger customer relationships</p></div><span className="pill orange-pill">3 insights</span></div><div className="insight-list">{[{title:'Prioritise network experience',desc:'Review complaints and service quality in Western Area.',Icon:Radio,color:'orange',tag:'High priority'},{title:'Reconnect with inactive wallets',desc:'Review Orange Money inactivity and plan a targeted outreach.',Icon:Wallet,color:'green',tag:'Opportunity'},{title:'Protect upcoming business renewals',desc:'Review B2B accounts approaching their contract renewal.',Icon:Building2,color:'purple',tag:'Retention'}].map(n=><div className="insight" key={n.title}><span className={`metric-icon ${n.color}`}><n.Icon size={18}/></span><div><strong>{n.title}</strong><p>{n.desc}</p></div><button onClick={()=>setNotice(`${n.title}: sample recommendation selected. Campaign execution is not connected.`)}>{n.tag}<ArrowUpRight size={14}/></button></div>)}</div></section></div>
  <aside className="right-column"><section className="panel drivers"><div className="panel-heading"><div><h2>What’s driving churn?</h2><p>Share of sample churn cases</p></div></div>{drivers.map(([label,value,color],i)=><div className="driver" key={label}><div><span>{i+1}. {label}</span><strong>{value}%</strong></div><div className="driver-track"><span style={{width:`${value*3}%`,background:color}}/></div></div>)}<p className="driver-note">Other factors account for 18.3%.</p></section><OmastaAssistant key={`${selected}-${userId}-${dataset.revision}`} department={selected} source={dataset.source} summary={customerSummary}/></aside></div>
  {page==='reports'&&<section className="panel report-panel"><h2>Download your department report</h2><p>Export the visible sample business metrics as a CSV file.</p><button className="primary-button" onClick={exportReport}><Download size={16}/>Download CSV</button></section>}
  </>}
  <footer><span>Orange Intelligence <i/> Sierra Leone</span><span>Better customer. A stronger Orange.</span></footer></main></div>
  {editing&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="access-title"><div className="panel-heading"><div><h2 id="access-title">Assign responsibilities</h2><p>{editing.name} · Department admin</p></div><button className="icon-button" aria-label="Close assignments" onClick={()=>setEditing(null)}><X size={20}/></button></div><div className="assignment-options">{departments.map(d=><label key={d}><input type="checkbox" checked={editing.departments.includes(d)} onChange={e=>setEditing({...editing,departments:e.target.checked?[...editing.departments,d]:editing.departments.filter(x=>x!==d)})}/><span>{d}</span><Check size={16}/></label>)}</div><p className="modal-note">Access changes are temporary and reset when this page reloads.</p><div className="modal-actions"><button className="secondary-button" onClick={()=>setEditing(null)}>Cancel</button><button className="primary-button" onClick={()=>{setUsers(users.map(u=>u.id===editing.id?editing:u));setNotice(`Responsibilities updated for ${editing.name}.`);setEditing(null);}}>Save assignments</button></div></section></div>}
  </div>;
}
